/**
 * JSON shapes returned by the server's REST API.
 *
 * These are type aliases into the generated OpenAPI types from
 * `@lukestanbery/jarvis-contracts` (single source of truth: `spec/openapi.yaml`,
 * regenerated by the contracts package's `npm run types`). The portal is
 * served as static assets, so only the *type* level of the contracts package is
 * imported — `import type` is erased at compile time and pulls nothing into the
 * bundle.
 */
import type { components } from "@lukestanbery/jarvis-contracts";

/** Account row as exposed by `/api/users`. */
export type ApiUser = components["schemas"]["User"];

/** Device credential row as exposed by `/api/me` and `/api/users/:id/devices`. */
export type ApiDevice = components["schemas"]["Device"];

/** Chat-thread session as exposed by `/api/sessions`. */
export type ApiSession = components["schemas"]["SessionSummary"];

/** Session echo (`GET /api/session`); carries the CSRF nonce when cookie-authenticated. */
export type SessionUser = components["schemas"]["Session"];

/** Cookie-login response (`POST /api/session`). */
export type SessionLogin = components["schemas"]["SessionLogin"];

/** Device-login response shared by `POST /api/bootstrap` and `POST /api/auth/login`. */
export type DeviceLogin = components["schemas"]["AuthResult"];

/** Device as issued by `POST /api/devices` and the device-login flows (one-time token). */
export type IssuedDevice = components["schemas"]["IssuedDevice"];

/** Free-form per-user integration prefs (`/api/prefs`). */
export type Prefs = components["schemas"]["Prefs"];
